environment: PROD
geocoding:
  host: mongo-revgeo
  port: 8889
db:
  host: 192.168.1.22
  db: blitzinfo
lightningMaps:
  baseUrl: wss://live2.lightningmaps.org
ports:
  rest: 5000
  socketIo: 5001
dupeChecking:
  timeout: 60